name: syncreve
description: Cross-platform file sync client for Cloudreve

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  riverpod: ^2.3.2
  dio: ^5.1.0
  fluttertoast: ^8.1.3
  flutter_easyloading: ^3.0.5
  pull_to_refresh_flutter3: ^2.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true